name:                haskell-stack-nix-example
version:             1.0.0.0
github:              "tweag/haskell-stack-nix-example"
author:              "Idris"
maintainer:          "Idris"
copyright:           "MIT"

description:         Valid and invalid Stack + Nix integration examples

dependencies:
  - base
  - turtle

library:
  source-dirs: src
